
// State: App
export const APP_SET_STATUS = 'APP_SET_STATUS';
export const APP_SET_LOADING = 'APP_SET_LOADING';
export const APP_SET_FETCHING = 'APP_SET_FETCHING';

// State: Store
export const STORE_SET_CATEGORIES = 'STORE_SET_CATEGORIES';
export const STORE_SET_VIEWPAGE = 'STORE_SET_VIEWPAGE';