
// State: App
export const APP_SET_STATUS = 'APP_SET_STATUS';
export const APP_SET_LOADING = 'APP_SET_LOADING';
export const APP_SET_FETCHING = 'APP_SET_FETCHING';

// State: Store
export const STORE_SET_CATEGORIES = 'STORE_SET_CATEGORIES';
export const STORE_SET_VIEWPAGE = 'STORE_SET_VIEWPAGE';

// State: User
export const USER_LOGIN = 'USER_LOGIN';
export const USER_LOGOUT = 'USER_LOGOUT';

// State: Modal
export const MODAL_LOGIN_TOGGLE = 'MODAL_LOGIN_TOGGLE';
export const MODAL_REGISTER_TOGGLE = 'MODAL_REGISTER_TOGGLE';
export const MODAL_REGISTER_COMPLETED_TOGGLE = 'MODAL_REGISTER_COMPLETED_TOGGLE';